#!/usr/bin/python3
import sys

def factorize(number):
    for i in range(2, number):
        if number % i == 0:
            return i
    return None


file = open("test00", "r")

for line in file:
    number = int(line)
    i  = factorize(number)
    print("{}={}*{}".format(number, number // i, i))
    

file.close()