#!/usr/bin/python3
import sys
import ctypes

fun = ctypes.CDLL("./libfactor.so")
factorize = fun.factorize
factorize.argtypes = [ctypes.c_int]
factorize.restype = ctypes.c_int

if len(sys.argv) != 2:
    print("Usage: factors <file>")
    sys.exit()

file = open(sys.argv[1], "r")

for line in file:
    number = int(line)
    i = factorize(number)
    print("{}={}*{}".format(number, number // i, i))


file.close()
